development: &non_production_settings
  :twitter:
    :consumer_key: "YOUR TWITTER CONSUMER KEY"
    :consumer_secret: "YOUR TWITTER CONSUMER SECRET"
    :oauth_token: "YOUR TWITTER OAUTH TOKEN"
    :oauth_token_secret: "YOUR TWITTER OAUTH TOEKN SECRET"
  :site:
    :title: "VinosPhilos"
    :address: "http://localhost:9393/"